packages:
  - packages/*
  - app/*

catalogs:
  dependencies: # Config for shared dependencies
    zod: 4.1.12
    dotenv: 16.4.7

  devDependencies: # Config for shared dev dependencies
    typescript: 5.7.3
    husky: ^9.1.7

overrides:
 
