packages:
  - packages/*
  - app/*

catalogs:
  dependencies: # Config for shared dependencies
    zod: 4.1.12
    dotenv: 16.4.7
    jest: ^29.7.0

  devDependencies: # Config for shared dev dependencies
    typescript: 5.7.3
    husky: ^9.1.7
    "@types/jest": ^29.5.2
    "@types/node": ^20.3.1
    "ts-jest": ^29.1.0
    "ts-node": ^10.9.1

overrides:
 
